CREATE TABLE profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255),
   username VARCHAR(255),
   password VARCHAR(255),
   role VARCHAR(255),
   active BOOLEAN               DEFAULT TRUE    NOT NULL,
   account_expired BOOLEAN      DEFAULT FALSE   NOT NULL,
   account_locked BOOLEAN       DEFAULT FALSE   NOT NULL,
   credentials_expired BOOLEAN  DEFAULT FALSE   NOT NULL,
   CONSTRAINT pk_profile PRIMARY KEY (id)
);

ALTER TABLE profile ADD CONSTRAINT uc_profile_username UNIQUE (username);

CREATE TABLE transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   uuid UUID,
   description VARCHAR(255),
   brlvalue DECIMAL,
   usdvalue DECIMAL,
   eurvalue DECIMAL,
   created_at TIMESTAMP,
   transaction_type VARCHAR(255),
   profile_id BIGINT,
   CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE transaction ADD CONSTRAINT FK_TRANSACTION_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profile (id);

CREATE TABLE currency (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   eur_value DECIMAL,
   usd_value DECIMAL,
   created_at TIMESTAMP,
   CONSTRAINT pk_currency PRIMARY KEY (id)
);